### ISSUE TITLE
Allow to disable the primary display

### ISSUE THREAD

**Issue by Borgotto** [MartinGC94/DisplayConfig#13]
Is it because of an API limitation that you don't allow to disable to primary display?
If not, could you add an optional parameter to forcefully impose it when calling `Disable-Display`?

https://github.com/MartinGC94/DisplayConfig/blob/c8ecaa72c87b0380ab0a92059b6e655980de5b49/src/DisplayConfig/API/DisplayConfig.cs#L519-L522

**Comment by Borgotto** [comment]
I was planning on disabling all displays to then create a virtual one.
This should let Windows make the virtual display the primary.

If I were to reverse the order of operations, creating the virtual display first, it would mess with the display indexes in a unpredictable way.
I don't know how I can add the virtual display, get its index reliably to set it as primary, then remove the others.

**Comment by MartinGC94** [comment]
You can use `Get-DisplayInfo` for this. The most reliable way would be like this:
```
$RealDisplays = Get-DisplayInfo
# Somehow add the virtual display
$VirtualDisplays = Get-DisplayInfo | Where-Object -Property DevicePath -NotIn $RealDisplays.DevicePath
```

Alternatively, if the virtual displays have a specific name you can do it like this: `$VirtualDisplays = Get-DisplayInfo | Where-Object -Property DisplayName -EQ "My virtual display"`
