### ISSUE TITLE
After installing 3.2 from nupkg, not command is available

### ISSUE THREAD

**Issue by waldner** [MartinGC94/DisplayConfig#14]
So with 3.1.0 I could download the nupkg file, copy it to my trusted local directory, install it with

```
Install-Module DisplayConfig -Scope AllUsers -Force -Repository LocalPackages -Verbose
```

and after that I could use all the available commands, and tab completion worked. With 3.2, same exact procedure, this is what happens:

```
PS C:\Windows\system32> Install-Module DisplayConfig -Scope AllUsers -Force -Repository LocalPackages -Verbose
VERBOSE: Repository details, Name = 'LocalPackages', Location = 'C:\pkgs'; IsTrusted = 'True'; IsRegistered = 'True'.
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
VERBOSE: Using the specified source names : 'LocalPackages'.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'C:\pkgs' and PackageManagementProvider is 'NuGet'.
VERBOSE: Total package yield:'1' for the specified package 'DisplayConfig'.
VERBOSE: Performing the operation "Install-Module" on target "Version '3.2.0' of module 'DisplayConfig'".
VERBOSE: The installation scope is specified to be 'AllUsers'.
VERBOSE: The specified module will be installed in 'C:\Program Files\WindowsPowerShell\Modules'.
VERBOSE: The specified Location is 'NuGet' and PackageManagementProvider is 'NuGet'.
VERBOSE: Downloading module 'DisplayConfig' with version '3.2.0' from the repository 'C:\pkgs'.
VERBOSE: InstallPackageLocal' - name='DisplayConfig', version='3.2.0',destination='C:\Users\admin\AppData\Local\Temp\1202131567'
VERBOSE: Catalog file 'DisplayConfig.cat' is not found in the contents of the module 'DisplayConfig' being installed.
VERBOSE: Module 'DisplayConfig' was installed successfully to path 'C:\Program Files\WindowsPowerShell\Modules\DisplayConfig\3.2.0'.
```

Everything seems fine, however tab completion doesn't work and no command is available:

```
PS C:\Windows\system32> Get-DisplayInfo
Get-DisplayInfo : The term 'Get-DisplayInfo' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Get-DisplayInfo
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-DisplayInfo:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

As I said earlier, I'm not really a PS expert but it seems odd to me that the same procedure stopped working with 3.2.

**Comment by waldner** [comment]
From what I can see, the only difference compared to the direct install from Powershell Gallery is that using my method installs under `C:\Program Files\WindowsPowerShell\Modules\DisplayConfig\3.2.0`, while installing from the gallery installs under `C:\Program Files\WindowsPowerShell\Modules\DisplayConfig\3.2` and the latter works.

**Comment by MartinGC94** [comment]
It's because there's a mismatch in the version I've specified in the module manifest (3.2) and the version specified in the folder name you've created (3.2.0). PowerShell for some odd reason is very particular about versions like that.
You need to fix your repository server or the way you import the module to the server so it handles versions with just Major.Minor properly.

**Comment by waldner** [comment]
I'm just downloading the nupkg from the gallery (which gets me `displayconfig.3.2.0.nupkg`), then I copy it to `C:\pkgs` (which I previously declared as trusted repo with:

```
Register-PSRepository -Name LocalPackages -SourceLocation C:\pkgs -InstallationPolicy Trusted
```

) then install with

```
Install-Module DisplayConfig -Scope AllUsers -Force -Repository LocalPackages -Verbose
```

I don't see any switch to help me control the target directory and/or the major.minor numbering.

Ok, I see that if I manually rename `C:\Program Files\WindowsPowerShell\Modules\DisplayConfig\3.2.0` to `C:\Program Files\WindowsPowerShell\Modules\DisplayConfig\3.2` then it starts working. I can live with that, but I'm reporting this just in case you think it can somehow be "fixed" or changed so no manual change is necessary (or perhaps investigate why it's installing under `3.2.0` instead of `3.2` in the first place, whatever).

Thanks!

**Comment by MartinGC94** [comment]
Good to know. I've never bothered looking into setting up a local repository but that seems surprisingly simple (though obviously not without flaws). From my side I can only try to make sure future releases include "Major.Minor.Patch".
