### ISSUE TITLE
DisplayConfig cannot execute via remote tool (Intune Win32app, SCCCM task scheduler, etc.)

### ISSUE THREAD

**Issue by poppyno1** [MartinGC94/DisplayConfig#15]
Hi Martin,
     I tested it works well after install the module on local laptop, but when I want to use it for bulk display config . There is nothing happen , the script just execute but the display resolution didn't change and apply.
     May I know if there is any limitation?

**Comment by MartinGC94** [comment]
It seems to be an API limitation, see this thread where another user has the same issue: https://stackoverflow.com/questions/36066380/getdisplayconfigbuffersizes-inside-local-windows-service

If I run it on my own system through task scheduler I can see that the path/mode array sizes are zero like he described. I don't check for that, so when I run `QueryDisplayConfig` with those parameters set to 0 it throws the invalid parameters error that my module currently output.
I may release an update in the future so it throws a better error message but I can't do anything to make it work in that scenario.

**Comment by poppyno1** [comment]
I see. thanks for your great help , let me try to find another way to achieve ...
