### ISSUE TITLE
Error on restoring a saved profile after reboot

### ISSUE THREAD

**Issue by mefranklin6** [MartinGC94/DisplayConfig#9]
Thank you for your time, this looks like a fantastic tool but I'm having issues restoring a saved configuration after reboot.  I'm using the commands mentioned in the readme.

Steps to reproduce:
1. Save a configuration
```powershell
Get-DisplayConfig | Export-Clixml C:\Temp\single_display.xml
```
2. Reboot the PC and log in
3. Try to restore the saved config
```powershell
Import-Module DisplayConfig
Import-Clixml C:\Temp\single_display.xml | Use-DisplayConfig -UpdateAdapterIds
```

This works fine without a reboot, but after a reboot it errors out:
```powershell
Use-DisplayConfig : The parameter is incorrect
At line:1 char:44
+ ... ixml C:\Temp\single_display.xml | Use-DisplayConfig -UpdateAdapterIds
+                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (MartinGC94.Disp...I.DisplayConfig:DisplayConfig) [Use-DisplayConfig], Win32Exception
    + FullyQualifiedErrorId : ConfigApplyError,MartinGC94.DisplayConfig.Commands.UseDisplayConfigCommand
 ```

This seems to error out regardless if I set the `-UpdateAdapterIds` flag or not, or skip the extra `Import-Module DisplayConfig` or not.

After exporting a Clixml again after reboot and comparing the diffs, it seems like there's plenty of changes.  I've attached before reboot xml `single_display.xml` and after reboot xml `new_single_display.xml`

(Note that this may be a bad example as I'm trying to restore "Clone" mode in the above xml and I know there's a direct way to do that in this tool, but I'm hoping to use this for multiple monitor computers as well)

Thank you!

**Comment by mefranklin6** [comment]
[single_display.xml.txt](https://github.com/user-attachments/files/17134651/single_display.xml.txt)
[new_single_display.xml.txt](https://github.com/user-attachments/files/17134652/new_single_display.xml.txt)
Attached XML's.  (Github does not like .xml so I added .txt at the end for upload)

**Comment by MartinGC94** [comment]
Thanks for the report. I'm currently working on a fix for another issue related to clone configs. I will let you know once it's ready so you can test out if it's still an issue with the new changes.

**Comment by MartinGC94** [comment]
I just tested this on my own system and it seems to work fine with the changes I've made here: https://github.com/MartinGC94/DisplayConfig/issues/6#issuecomment-2380285724

Can you give that version a try and see if it works for you?
If it doesn't work please do what you did before with a before and after config but for the after config, try to manually set up the displays like you had them when you exported the "before" version.

**Comment by mefranklin6** [comment]
Works great on the test bench!  Also those new features are useful, thank you very much for your dedication to this project!  

My plan is to deploy this to about 400 PC's eventually, so I'll let you know if I find any edge cases.  I'll also try and contribute when possible since this is going to be a very valuable tool.

**Comment by soleous** [comment]
I'm getting this error after coming out of standby.  A reboot appears to resolve it.  Is this known?

**Comment by MartinGC94** [comment]
Nope, it's not a problem I'm aware of. Feel free to open a new issue with more details. It would especially be nice with an exported config before and after coming out of standby.
